name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: 'script -q -e -c "bash {0}"'
    env:
      CPPFLAGS: -Wno-unknown-pragmas -Wno-unused-but-set-variable -Wno-unused-function
    steps:
    - uses: actions/checkout@v3.0.0
      with:
        repository: 'stardustxr/stardust-xr'
        submodules: 'recursive'
    - uses: actions/setup-python@v3.1.0
    - name: Caching time
      uses: actions/cache@v3.0.1
      id: caching-time
      with:
        path: |
          flatbuffers/
          /home/runner/.cache/pip
        key: wheeeeeeeeeeeeeeeee

    - name: Clone/Build Flatbuffers
      if: steps.caching-time.outputs.cache-hit != 'true'
      run: |
        git clone https://github.com/google/flatbuffers.git
        cd flatbuffers/
        #git checkout bf17df346e368918b2382ae3f451dc47f4c12f77
        cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release -DFLATBUFFERS_BUILD_TESTS=OFF -DFLATBUFFERS_BUILD_FLATC=OFF -DFLATBUFFERS_BUILD_FLATHASH=OFF -DFLATBUFFERS_BUILD_SHAREDLIB=ON -DCMAKE_INSTALL_PREFIX=/usr
        make -j2
    - name: Install Flatbuffers
      run: |
        cd flatbuffers/
        sudo make install
    
    - name: Install Meson
      run: |
        python3 -m pip install meson==0.62.0

    - name: Install Ninja
      uses: seanmiddleditch/gha-setup-ninja@v3

    
    - name: Install Stardust dependencies
      run: |
        sudo apt install -y libxkbcommon-dev #mesa-common-dev libwayland-egl1 libgles2-mesa-dev libgl1-mesa-dev libglu1-mesa-dev fontconfig
        sudo apt install wayland-protocols libwayland-dev libegl1-mesa-dev libgles2-mesa-dev libdrm-dev libgbm-dev libinput-dev libxkbcommon-dev libgudev-1.0-dev libpixman-1-dev libsystemd-dev libpng-dev libavutil-dev libavcodec-dev libavformat-dev # wlroots dependencies

    - name: Install wayland-protocols
      run: |
        git clone --branch 1.25 --depth=1 https://gitlab.freedesktop.org/wayland/wayland-protocols
        cd wayland-protocols/
        meson build
        ninja -j2 -C build
        sudo $(which ninja) -j2 -C build install

    - name: Install libdrm
      run: |
        curl -fsSL https://dri.freedesktop.org/libdrm/libdrm-2.4.110.tar.xz | tar -xJ
        cd libdrm-2.4.110/
        meson build
        ninja -C build -j2
        sudo $(which ninja) -C build -j2 install

    - name: Install wayland
      run: |
        git clone --branch 1.20.0 https://gitlab.freedesktop.org/wayland/wayland
        cd wayland
        meson build -Ddocumentation=false
        ninja -j2 -C build
        sudo $(which ninja) -C build -j2 install

    - name: Install libseat
      run: |
        git clone --branch 0.6.4 https://git.sr.ht/~kennylevinsen/seatd
        cd seatd
        meson build
        ninja -j2 -C build
        sudo $(which ninja) -C build -j2 install

    - name: Install libstardustxr
      run: |
        git clone https://github.com/StardustXR/libstardustxr.git
        cd libstardustxr/
        git checkout 3c13374c7f1eb68151bfca421533d31a23542ee3
        meson build
        ninja -C build -j2
        sudo $(which ninja) -C build -j2 install
    
    - name: Build Server
      uses: BSFishy/meson-build@v1.0.3
      with:
        action: build
        directory: build
        meson-version: 0.53.0
        options: -j2
